name: Publish Docker

on:
  push:
    branches: [main]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert repository name to lower case
      run: echo IMAGE_REPOSITORY="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

    - name: Build Image
      run: docker build . -t ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest

    - name: Push Image
      run: docker push ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
